pipeline {

    agent any

    tools {
        maven 'Maven-3'
        jdk 'JDK-11'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Building Application"

                dir('app') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Package') {
            steps {
                echo "Packaging WAR"

                dir('app') {
                    sh 'mvn clean package -DskipTests'
                }

                archiveArtifacts artifacts: 'app/target/*.war'
            }
        }

        stage('Debug') {
            steps {
                sh '''
                echo "Current User:"
                whoami

                echo "Current Directory:"
                pwd

                echo "PATH:"
                echo $PATH

                echo "Ansible Location:"
                which ansible-playbook

                echo "Ansible Version:"
                /usr/bin/ansible-playbook --version
                '''
            }
        }

        stage('Deploy') {
            steps {

                echo "Deploying Application using Ansible"

                sh '''
                export PATH=/usr/bin:$PATH

                cp app/target/devops-e2e-app.war ansible/files/

                /usr/bin/ansible-playbook \
                  -i ansible/inventory.ini \
                  ansible/site.yml
                '''
            }
        }

        stage('Health Check') {
            steps {

                echo "Checking Application Health"

                sh '''
                chmod +x scripts/health_check.sh

                ./scripts/health_check.sh 40.81.24.106
                '''
            }
        }
    }

    post {

        success {
            echo "Pipeline executed successfully."
        }

        failure {
            echo "Pipeline execution failed."
        }

        always {
            echo "Pipeline completed."
        }
    }
}
