pipeline {

    agent any

    tools {
        maven 'Maven-3'
        jdk 'JDK-11'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Building Application"

                dir('app') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Package') {
            steps {

                echo "Packaging WAR (Skipping Tests)"

                dir('app') {
                    sh 'mvn clean package -DskipTests'
                }

                archiveArtifacts artifacts: 'app/target/*.war'
            }
        }

        stage('Deploy') {
            steps {

                echo "Deploying Application using Ansible"

                sh '''
                cp app/target/devops-e2e-app.war ansible/files/

                ansible-playbook \
                -i ansible/inventory.ini \
                ansible/site.yml
                '''
            }
        }

        stage('Health Check') {
            steps {

                echo "Checking Application Health"

                sh '''
                chmod +x scripts/health_check.sh

                ./scripts/health_check.sh 40.81.24.106
                '''
            }
        }
    }

    post {

        success {
            echo "Pipeline executed successfully."
        }

        failure {
            echo "Pipeline execution failed."
        }

        always {
            echo "Pipeline completed."
        }
    }
}
